[package]
name = "simple_api"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4"
diesel = { version = "1.4", features = ["postgres"] }
dotenv = "0.15"
env_logger = "0.9"
serde = "1.0"
serde_derive = "1.0"

